version: "3.7"

services: 
  db:
    image: postgres
    container_name: db 
    expose:
      - "3306"
    ports: 
      - "5432:5432"
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=OrdersDB
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: pastecco-pedidos
    ports: 
      - "5000:5000"
    volumes:
      - .:/usr/app      
      - /usr/src/app/node_modules
    links: 
      - db
    depends_on:
      - db

volumes: 
  pgdata: 
    driver: local
